name: RDP Access with Gmail Notification

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Tailscale
        run: |
          choco install tailscale -y
          tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --hostname=github-rdp --accept-routes --accept-dns=false

      - name: Enable Remote Desktop
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Create RDP User
        run: |
          $password = -join ((33..126) | Get-Random -Count 12 | % {[char]$_})
          net user RDP $password /add
          net localgroup administrators RDP /add
          echo "User: RDP | Password: $password" | Out-File -FilePath rdp.txt
          echo "RDP_CREDS=$(Get-Content rdp.txt)" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Get Tailscale IP
        id: tailscale-ip
        run: |
          $ip = (tailscale ip -4 | Select-String '^100\.' | Select-Object -First 1).ToString()
          echo "TAILSCALE_IP=$ip" | Out-File -FilePath $env:GITHUB_ENV -Append
          Write-Host "RDP will be available at $ip"

      - name: Verify RDP Accessibility
        run: |
          Write-Host "Tailscale IP: $env:TAILSCALE_IP"
          $testResult = Test-NetConnection -ComputerName $env:TAILSCALE_IP -Port 3389
          if (-not $testResult.TcpTestSucceeded) {
              Write-Error "TCP connection to RDP port 3389 failed"
              exit 1
          }
          Write-Host "TCP connectivity successful!"

      - name: Send RDP details via Gmail
        if: success()
        env:
          SMTP_USER: ${{ secrets.EMAIL_SMTP_USER }}
          SMTP_PASS: ${{ secrets.EMAIL_SMTP_PASS }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: |
          $ip = $env:TAILSCALE_IP
          $creds = (Get-ChildItem env:RDP_CREDS).Value
          $subject = "RDP Access — $ip"
          $body = @"
          RDP ACCESS DETAILS

          Address: $ip
          $creds

          (Sent automatically from GitHub Actions.)
          "@

          $smtp = New-Object System.Net.Mail.SmtpClient("smtp.gmail.com", 587)
          $smtp.EnableSsl = $true
          $smtp.Credentials = New-Object System.Net.NetworkCredential($env:SMTP_USER, $env:SMTP_PASS)

          $msg = New-Object System.Net.Mail.MailMessage($env:EMAIL_FROM, $env:EMAIL_TO, $subject, $body)
          $msg.IsBodyHtml = $false

          try {
            $smtp.Send($msg)
            Write-Host "RDP details sent to Gmail"
          } catch {
            Write-Error "Failed to send email: $_"
            exit 1
          }

      - name: Keep Session Alive
        run: |
          while ($true) { Start-Sleep -Seconds 300 }
